### ISSUE TITLE
Can I use different created_at field in several model

### ISSUE THREAD

**Issue by jonathanoeijoeng** [laracraft-tech/laravel-date-scopes#5]
What if I have several model that I want to use DateScope but each model will use different "created_at" field i.e day_submission field.

Thanks

**Comment by Sairahcaz** [comment]
Hi @jonathanoeijoeng, I'll add that this week, I hope!

**Comment by Sairahcaz** [comment]
Hi @jonathanoeijoeng this should now work in the latest release!

**Comment by jonathanoeijoeng** [comment]
Great!! How to choose different created_at field? I cannot find it in changelog.

**Comment by Sairahcaz** [comment]
@jonathanoeijoeng it's basically just changing the `CREATED_AT` constant in your model.
I added it here in the README: https://github.com/laracraft-tech/laravel-date-scopes#fluent-created_at-column-configuration
